# Generated by Django 5.0.6 on 2024-06-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdates',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
